version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python app.py
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    pull_policy: always
